name: HubWorks
options:
  bundleIdPrefix: com.cedricziel.hubworks
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
    watchOS: "26.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.42.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  skipPackagePluginValidation: true

packages:
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.17.0"
  swift-dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.0.0"
  swift-concurrency-extras:
    url: https://github.com/pointfreeco/swift-concurrency-extras
    from: "1.0.0"
  swift-identified-collections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: "1.0.0"
  swift-case-paths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: "1.0.0"

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    SWIFT_STRICT_CONCURRENCY: complete
    SKIP_MACRO_VALIDATION: true
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule

targetTemplates:
  Framework:
    type: framework
    settings:
      base:
        DEFINES_MODULE: true
        GENERATE_INFOPLIST_FILE: true

targets:
  # MARK: - iOS App
  HubWorks-iOS:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Apps/HubWorks-iOS
        excludes:
          - "*.entitlements"
    dependencies:
      - target: HubWorksCore_iOS
      - target: HubWorksFeatures_iOS
      - target: HubWorksUI_iOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-identified-collections
        product: IdentifiedCollections
      - package: swift-case-paths
        product: CasePaths
    entitlements:
      path: Apps/HubWorks-iOS/HubWorks-iOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.cedricziel.hubworks
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.cedricziel.hubworks
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.cedricziel.hubworks
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks
        INFOPLIST_FILE: Apps/HubWorks-iOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Apps/HubWorks-iOS/HubWorks-iOS.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WPW3QSLZ2F
        PRODUCT_NAME: HubWorks
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Apps/HubWorks-iOS/Info.plist
      properties:
        CFBundleDisplayName: HubWorks
        CFBundleName: HubWorks
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIBackgroundModes:
          - fetch
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - com.cedricziel.hubworks.refresh
        NSFaceIDUsageDescription: "HubWorks uses Face ID to protect your GitHub accounts"
        GitHubClientID: $(GITHUB_CLIENT_ID)
        GitHubClientSecret: $(GITHUB_CLIENT_SECRET)
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - hubworks
            CFBundleURLName: com.cedricziel.hubworks.oauth
        LSApplicationCategoryType: public.app-category.developer-tools

  # MARK: - macOS App
  HubWorks-macOS:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Apps/HubWorks-macOS
        excludes:
          - "*.entitlements"
    dependencies:
      - target: HubWorksCore_macOS
      - target: HubWorksFeatures_macOS
      - target: HubWorksUI_macOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-identified-collections
        product: IdentifiedCollections
      - package: swift-case-paths
        product: CasePaths
    entitlements:
      path: Apps/HubWorks-macOS/HubWorks-macOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.cedricziel.hubworks
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.ubiquity-kvstore-identifier: $(TeamIdentifierPrefix)com.cedricziel.hubworks
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.cedricziel.hubworks
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.macos
        INFOPLIST_FILE: Apps/HubWorks-macOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Apps/HubWorks-macOS/HubWorks-macOS.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WPW3QSLZ2F
        PRODUCT_NAME: HubWorks
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    info:
      path: Apps/HubWorks-macOS/Info.plist
      properties:
        CFBundleDisplayName: HubWorks
        CFBundleName: HubWorks
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        NSHumanReadableCopyright: "Copyright © 2025 HubWorks. All rights reserved."
        GitHubClientID: $(GITHUB_CLIENT_ID)
        GitHubClientSecret: $(GITHUB_CLIENT_SECRET)
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - hubworks
            CFBundleURLName: com.cedricziel.hubworks.oauth
        LSApplicationCategoryType: public.app-category.developer-tools

  # MARK: - watchOS App
  HubWorks-watchOS:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: Apps/HubWorks-watchOS
        excludes:
          - "*.entitlements"
    dependencies:
      - target: HubWorksCore_watchOS
      - target: HubWorksUI_watchOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
    entitlements:
      path: Apps/HubWorks-watchOS/HubWorks-watchOS.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.cedricziel.hubworks
        com.apple.developer.icloud-services:
          - CloudKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.watchos
        INFOPLIST_FILE: Apps/HubWorks-watchOS/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Apps/HubWorks-watchOS/HubWorks-watchOS.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: WPW3QSLZ2F
        PRODUCT_NAME: HubWorks
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: Apps/HubWorks-watchOS/Info.plist
      properties:
        CFBundleDisplayName: HubWorks
        CFBundleName: HubWorks
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        WKApplication: true

  # MARK: - iOS Frameworks
  HubWorksCore_iOS:
    templates:
      - Framework
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksCore
    dependencies:
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-dependencies
        product: DependenciesMacros
      - package: swift-concurrency-extras
        product: ConcurrencyExtras
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.core
        PRODUCT_NAME: HubWorksCore
        PRODUCT_MODULE_NAME: HubWorksCore

  HubWorksFeatures_iOS:
    templates:
      - Framework
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksFeatures
    dependencies:
      - target: HubWorksCore_iOS
      - target: HubWorksUI_iOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-identified-collections
        product: IdentifiedCollections
      - package: swift-case-paths
        product: CasePaths
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.features
        PRODUCT_NAME: HubWorksFeatures
        PRODUCT_MODULE_NAME: HubWorksFeatures

  HubWorksUI_iOS:
    templates:
      - Framework
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksUI
    dependencies:
      - target: HubWorksCore_iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.ui
        PRODUCT_NAME: HubWorksUI
        PRODUCT_MODULE_NAME: HubWorksUI

  # MARK: - macOS Frameworks
  HubWorksCore_macOS:
    templates:
      - Framework
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksCore
    dependencies:
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-dependencies
        product: DependenciesMacros
      - package: swift-concurrency-extras
        product: ConcurrencyExtras
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.core
        PRODUCT_NAME: HubWorksCore
        PRODUCT_MODULE_NAME: HubWorksCore

  HubWorksFeatures_macOS:
    templates:
      - Framework
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksFeatures
    dependencies:
      - target: HubWorksCore_macOS
      - target: HubWorksUI_macOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-identified-collections
        product: IdentifiedCollections
      - package: swift-case-paths
        product: CasePaths
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.features
        PRODUCT_NAME: HubWorksFeatures
        PRODUCT_MODULE_NAME: HubWorksFeatures

  HubWorksUI_macOS:
    templates:
      - Framework
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksUI
    dependencies:
      - target: HubWorksCore_macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.ui
        PRODUCT_NAME: HubWorksUI
        PRODUCT_MODULE_NAME: HubWorksUI

  # MARK: - watchOS Frameworks
  HubWorksCore_watchOS:
    templates:
      - Framework
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksCore
    dependencies:
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-dependencies
        product: Dependencies
      - package: swift-dependencies
        product: DependenciesMacros
      - package: swift-concurrency-extras
        product: ConcurrencyExtras
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.core
        PRODUCT_NAME: HubWorksCore
        PRODUCT_MODULE_NAME: HubWorksCore

  HubWorksUI_watchOS:
    templates:
      - Framework
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/HubWorksUI
    dependencies:
      - target: HubWorksCore_watchOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.ui
        PRODUCT_NAME: HubWorksUI
        PRODUCT_MODULE_NAME: HubWorksUI

  # MARK: - Tests
  HubWorksCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/HubWorksCoreTests
    dependencies:
      - target: HubWorksCore_iOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.core.tests

  HubWorksFeaturesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/HubWorksFeaturesTests
    dependencies:
      - target: HubWorksFeatures_iOS
      - target: HubWorksCore_iOS
      - package: swift-composable-architecture
        product: ComposableArchitecture
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cedricziel.hubworks.features.tests

schemes:
  HubWorks-iOS:
    build:
      targets:
        HubWorks-iOS: all
        HubWorksCore_iOS: all
        HubWorksFeatures_iOS: all
        HubWorksUI_iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HubWorksCoreTests
        - HubWorksFeaturesTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  HubWorks-macOS:
    build:
      targets:
        HubWorks-macOS: all
        HubWorksCore_macOS: all
        HubWorksFeatures_macOS: all
        HubWorksUI_macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HubWorksCoreTests
        - HubWorksFeaturesTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  HubWorks-watchOS:
    build:
      targets:
        HubWorks-watchOS: all
        HubWorksCore_watchOS: all
        HubWorksUI_watchOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
